# Base configuration for vault-app example
# These properties come from the standard config source

spring:
  application:
    name: "vault-app"

server:
  port: 8090

app:
  title: "Vault Integration Example"
  description: "Demonstrates filtering properties by source (simulating Vault)"
  version: "1.0.0"

# Non-sensitive configuration
database:
  host: "db.example.com"
  port: 5432
  name: "vault_demo_db"
  maxConnections: 30

features:
  enableCache: true
